language: android
install: true
sudo: false

jdk:
    - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

android:
  components:
    - tools
    - build-tools-26.0.1
    - android-26
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services

cache:
  directories:
    - $HOME/.gradle

notifications:
  email: false

before_script:
  - chmod +x gradlew

script:
  - ./gradlew build

after_success:
  - ./gradlew jacocoTestReport && bash <(curl -s https://codecov.io/bash)
